# Generated by Django 3.1.7 on 2021-04-02 16:32

from django.db import migrations, models
import django.db.models.deletion
import literakiapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=literakiapp.models.randid, max_length=32, unique=True)),
                ('max_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=literakiapp.models.randid, max_length=32, unique=True)),
                ('name', models.CharField(default=literakiapp.models.randname, max_length=32)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literakiapp.game')),
            ],
        ),
    ]
