# Generated by Django 3.1.7 on 2021-04-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literakiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literakiapp.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literakiapp.player')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
    ]
