# Generated by Django 3.1.7 on 2021-04-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literakiapp', '0005_auto_20210403_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='state',
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
