# Generated by Django 3.1.7 on 2021-04-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literakiapp', '0008_auto_20210403_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_game', to='literakiapp.playeringame'),
        ),
        migrations.AddField(
            model_name='game',
            name='voting',
            field=models.BooleanField(default=False),
        ),
    ]
