# Generated by Django 3.1.7 on 2021-04-07 22:19

from django.db import migrations, models
import django.db.models.deletion
import literakiapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('literakiapp', '0010_auto_20210407_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='token',
            field=models.CharField(default=literakiapp.models.randid, max_length=32),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='vote',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='letteronboard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literakiapp.playeringame'),
        ),
    ]
