# production config for use with nginx reverse proxy
# base config: docker-compose.yml

version: '3.8'

services:
  nginx:
    hostname: literaki
    expose:
      - 80
    networks:
      - default
      - reverse_default

networks:
  reverse_default:
    external: true
