version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 8000 literaki.asgi:application
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./env/prod-web.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/prod-db.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./.certbot/conf:/etc/letsencrypt
      - ./.certbot/www:/var/www/certbot
    env_file:
      - ./env/prod-nginx.env
    expose:
      - 80
      - 443
    restart: always
    depends_on:
      - web
  redis:
    image: "redis:alpine"
    restart: always
    expose: 
      - 6379
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./.certbot/conf:/etc/letsencrypt
      - ./.certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"

volumes:
  postgres_data:
  static_volume:
