version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 8000 literaki.asgi:application
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./env/prod-web.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/prod-db.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 80
    depends_on:
      - web
  redis:
    image: "redis:alpine"
    expose: 
      - 6379

volumes:
  postgres_data:
  static_volume:
