# Generated by Django 3.1.7 on 2021-04-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literakiapp', '0003_remove_game_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='letters',
            field=models.CharField(default='aaaaaaaaaąbbcccćdddeeeeeeeęfgghhiiiiiiiijjkkklllłłmmmnnnnnńooooooóppprrrrssssśtttuuwwwwyyyyzzzzzźż  ', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='letters',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.CreateModel(
            name='LetterOnBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literakiapp.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literakiapp.player')),
            ],
        ),
    ]
