# Generated by Django 3.1.7 on 2021-04-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literakiapp', '0004_auto_20210402_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='letteronboard',
            name='letter',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playeringame',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='letteronboard',
            unique_together={('game', 'x', 'y')},
        ),
    ]
