# Generated by Django 3.1.7 on 2021-04-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literakiapp', '0006_auto_20210403_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeringame',
            name='letters',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
