# Generated by Django 3.1.7 on 2021-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literakiapp', '0009_auto_20210406_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='left',
            field=models.BooleanField(default=False),
        ),
    ]
